### ISSUE TITLE
Add option return for request dictionary on calls

### ISSUE THREAD

**Issue by limx0** [betcode-org/betfair#106]
Would you be interested in adding functionality like this (or does it exist and I am missing it again..)? https://github.com/limx0/btcmarkets#even-more-control

Basically, I have an optional arg that allows the api to simply build a dict of the request to be sent, but allows the user more control over which http library they use, rather than being tied to requests.

This is useful for async workflows, and particularly important when doing Inplay betting (don't want code to be handing while your order inserts)

Thoughts?

**Comment by rozzac90** [comment]
#107 quick implementation of this.

**Comment by liampauling** [comment]
I have seen in other languages (golang) that sometimes a wrapper offers the option to provide an http client, would this work for you? With the default being requests.

**Comment by limx0** [comment]
Not quite because the async function signature is different. If there was an easy way to overload the functions I definitely would
