### ISSUE TITLE
Encoding password and certs in windows 10

### ISSUE THREAD

**Issue by csaiedu** [betcode-org/betfair#189]
Hi 
1) Have successfully created an AppKey and would like to login with encoded username and password in windows 10. 

2) Also when testing with 

```
trading = betfairlightweight.APIClient('username', 'password', app_key='app_key')
trading.login()

```

I get the certs error despite having copied the certificate in c:\certs\

APIError: None 
Params: None 
Exception: Certificate folder not found in /certs/

Could you help with that please?

Looking forward using the API

Thanks

**Comment by csaiedu** [comment]
Perfect, thanks. Any idea about the encoding of passwords etc? Also how is the 2-factor authentication handled?

Best regards

**Comment by liampauling** [comment]
Not sure what you mean by encoding as all requests are sent vis json which is utf-8.

2-factor is replaced by the use of certificates / appKey here as it its not really viable to have 2-factor when using an API.
