### ISSUE TITLE
Batb odds not displaying when streaming

### ISSUE THREAD

**Issue by sunb2021** [betcode-org/betfair#481]
Hi, I am running the sample code from examplestreaming.py, but have noticed that in some instances the current matched odds are not displaying when streaming.

Current example is marketId 1.200858762. Matched odds for FIRST_HALF_OVER_05 is 1.29, however, I am receiving all other offers (1.24, and 1.47) and not 1.29. I have tried setting the ladder level to 1, but the issue still remains.

`market_filter = streaming_market_filter(
    market_ids= ['1.200858762'],
    event_type_ids=["1"],
    market_types=["FIRST_HALF_GOALS_05"]
)`

`market_data_filter = streaming_market_data_filter(
    fields=["EX_BEST_OFFERS"], ladder_levels=3
)`

Streaming returned:

1.200858762 [{'batb': [[0, 3.5, 5.28], [1, 3.45, 26.8]], 'batl': [[0, 4.4, 5.14]], 'id': 5851482}, {'batb': [[0, 1.24, 317.88]], 'batl': [[0, 1.47, 30.33]], 'id': 5851483}]

![image](https://user-images.githubusercontent.com/78015060/177931547-9cc8f37e-4c4c-4f81-8ef1-cbafb521e419.png)

**Comment by liampauling** [comment]
You are seeing cross matching on the website and potentially some rolling up depending on your settings, you can ask for that with `EX_BEST_OFFERS_DISP`, more info [here](https://docs.developer.betfair.com/display/1smk3cen4v3lu3yomq5qye0ni/Exchange+Stream+API#ExchangeStreamAPI-Marketdatafieldfiltering/MarketDataFilter)  

Feel free to join the slack to discuss further.

**Comment by sunb2021** [comment]
Well... that solved that. `EX_BEST_OFFERS_DISP` went completely past me. Skimmed through it and thought it was for virtual bets for some reason or another.  Apologies and thank you very much.
