### ISSUE TITLE
market_definition returns None

### ISSUE THREAD

**Issue by sunb2021** [betcode-org/betfair#482]
I may be missing something fundamental here, but when running examplestreaming.py market_definitions are returning None. Below is the only difference.

`market_filter = streaming_market_filter(
    market_ids= Final(),
    event_type_ids=["1"],
    market_types=["FIRST_HALF_GOALS_05"]
)`

`market_data_filter = streaming_market_data_filter(
    fields=["EX_BEST_OFFERS_DISP"], ladder_levels=1
)`

Appreciate any help with this,
thank you.

**Comment by liampauling** [comment]
`EX_MARKET_DEF` [same link](https://docs.developer.betfair.com/display/1smk3cen4v3lu3yomq5qye0ni/Exchange+Stream+API#ExchangeStreamAPI-Marketdatafieldfiltering/MarketDataFilter)

**Comment by sunb2021** [comment]
Thanks Liam, I had tried that, but the following is returned, `<betfairlightweight.resources.streamingresources.MarketDefinition object at 0x000001CF58AC8D30>`

**Comment by liampauling** [comment]
Yep that is correct, use your debugger to inspect or use `lightweight=True` if you want the raw dictionary
