### ISSUE TITLE
Question about JSON conversion

### ISSUE THREAD

**Issue by jeffreybeen90** [betcode-org/betfair#496]
@liampauling 
Hi Paul, I am Jeffrey nice to meet you. I am a pyhton developer and I want to write some code that automatically processes betfair historic data. I want to convert the JSON files you can download from betfair in batch to csv files so I can analyze them. But I do not know how the conversion is made. Could you help me with this, maybe clarify some code? I just wonder how the betfair historic data processor works. 

Please contact me, my email is: jeffreybeen90@gmail.com
Many thanks, hope to hear from you,
cheers, Jeffrey

**Comment by liampauling** [comment]
Paul?

Feel free to join the slack group (readme) where it will be easier to discuss how it works, probably worth noting that it is not far off the code detailed in the examples.
