### ISSUE TITLE
Flumine seems stuck in orderstream handle_output

### ISSUE THREAD

**Issue by emagruppi** [betcode-org/betfair#541]
It seems like Flumine does not return currently active market.

Little debugging from my side suggests the issue comes from orderstream.py where the handle output does not really handle live events as it should.

Likely I am missing something here but cant get around the issue.

Any idea of what is happening?

**Comment by liampauling** [comment]
Have any more information / code related to this problem? Not sure I understand.

**Comment by liampauling** [comment]
Delayed key issue / oos.
