### ISSUE TITLE
`ssl.wrap_socket` removed in python 3.12

### ISSUE THREAD

**Issue by synapticarbors** [betcode-org/betfair#550]
Just a heads up that `ssl.wrap_socket` is removed in python 3.12 after being deprecated in python 3.7:
https://docs.python.org/3.11/library/ssl.html#ssl.wrap_socket

This breaks the streaming client. The solution is to create a ssl context and use that to wrap the socket:
https://docs.python.org/3.12/library/ssl.html#socket-creation

**Comment by liampauling** [comment]
Thanks for this, I have something working but its disabling the checks/verification, unsure if its just me..

```python
    def _create_socket(self) -> socket.socket:
        """Creates ssl socket, connects to stream api and
        sets timeout.
        """
        context = ssl.SSLContext(ssl.PROTOCOL_TLS_CLIENT)
        context.check_hostname = False
        context.verify_mode = ssl.CERT_NONE
        s = context.wrap_socket(
            socket.socket(socket.AF_INET, socket.SOCK_STREAM), server_hostname=self.host
        )
        s.settimeout(self.timeout)
        s.connect((self.host, self.__port))
        return s
```

**Comment by synapticarbors** [comment]
@liampauling -- any update on this?
